# Generated by Django 4.1.7 on 2023-06-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
