# Generated by Django 4.1.7 on 2023-06-09 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_alter_assets_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='id',
            new_name='asset_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='employee_id',
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='Employee.assets')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Employee.employee')),
            ],
        ),
    ]
