# Generated by Django 4.2.4 on 2023-08-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_rename_id_assets_asset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='name',
            field=models.CharField(default='asset', max_length=100, unique=True),
        ),
    ]
