# Generated by Django 4.2.4 on 2023-08-15 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_rename_name_assets_asset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='asset_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='Employee.assets'),
        ),
    ]
