# Generated by Django 4.2.4 on 2023-08-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_days',
            field=models.IntegerField(default=30),
        ),
    ]
